export const GET_LIST_COMPANY = 'GET_LIST_COMPANY';
export const GET_LIST_TYPICAL_COMPANY = 'GET_LIST_TYPICAL_COMPANY';
export const GET_LIST_TYPICAL_COMPANY_FROM_DATABASE = 'GET_LIST_TYPICAL_COMPANY_FROM_DATABASE';
export const GET_LIST_SUGGEST_COMPANY = 'GET_LIST_SUGGEST_COMPANY';
