export const LIST_POST = 'LIST_POST';
export const DETAIL_POST = 'DETAIL_POST';
export const TOTAL_POST = 'TOTAL_POST';
export const LIST_POSTSERVICE = 'LIST_POSTSERVICE';
export const LIST_POSTPORTFOLIO = 'LIST_POSTPORTFOLIO';
export const LIST_POSTPRODUCT = 'LIST_POSTPRODUCT';
